### ISSUE TITLE
Use the advanced-cache.php (or object-cache.php) to get rid of wp-config.php modification

### ISSUE THREAD

**Issue by anttiviljami** [anttiviljami/wp-safe-updates#17]
There's also a possibility to get rid of `db.php` as well by plugging into the advanced-cache.php file, which has the ability to modify the global $table_prefix variable since it gets loaded before `wp_set_wpdb_vars();`

**Comment by anttiviljami** [comment]
Thanks @ideag for pointing this possibility out :)

**Comment by onnimonni** [comment]
This seems like a very good idea since `advanced-cache.php` is not used so often.

If someone needs to use `advanced-cache.php` they could just modify that file to include `wp-safe-updates` as `mercator` does in `sunrise.php`:
```php
// Default mu-plugins directory if you haven't set it
defined( 'WPMU_PLUGIN_DIR' ) or define( 'WPMU_PLUGIN_DIR', WP_CONTENT_DIR . '/mu-plugins' );

// Also load mercator for domain mapping
require WPMU_PLUGIN_DIR . '/mercator/mercator.php';
```

**Comment by anttiviljami** [comment]
Upon more investigation advanced-cache.php won't work since we need to enable it via a constant and filter. object-cache.php is a better candidate.

**Comment by ideag** [comment]
Actually, plugin could modify `advanced-cache.php` and append it's stuff automatically if it is not there. It's a simple string match.

**Comment by anttiviljami** [comment]
@ideag no, the problem is we still need to define WP_CACHE in wp-config.php for advanced-cache.php to be loaded.

**Comment by ideag** [comment]
@anttiviljami yeah, i meant `object-cache.php` :) But the point about doing automatic check-and-append still stands.

**Comment by anttiviljami** [comment]
Ah, ok :+1: Yes, definitely
